Bio updates 2023
open-resources/physics_bank pull request #69
Opened 2023-05-30 06:09 UTC by naclsodium

Please let me know if there is any information I got wrong or missed in the bio!

2023-05-30 08:38 UTC, firasm requested changes
See small set of changes - thanks!

2023-05-30 08:38 UTC, firasm commented on files/bio.md
> +| Skyler Sattarifard | certainlyskyler|
Could you add the new names **after** Jake Bobowski, and before Ava?  That way it'll roughly be in chronological order.

2023-05-30 08:38 UTC, firasm commented on files/bio.md
> +Aside from academia, I usually rewatch sitcoms, Modern Family, The Big Bang Theory and Brooklyn Nine-Nine are my favorites. I also like to improve and expand my speedcubing skills. I also like to col
Could you collapse these into one paragraph instead of three? Do so for this one as well as Larita's

2023-05-30 08:38 UTC, firasm commented on files/bio.md
> +Aside from academia, I usually rewatch sitcoms, Modern Family, The Big Bang Theory and Brooklyn Nine-Nine are my favorites. I also like to improve and expand my speedcubing skills. I also like to col
Update: actually I noticed a lot of the newer bios are multi-paragraph, just collapse them into one paragraph please (by remove extra line breaks!)

2023-05-30 22:28 UTC, certainlyskyler commented
could you please update mine to "I am an upcoming second-year student intending to specialize in computer science. The two things I love the most are helping and learning, which is why I'm here. I'm particularly enthusiastic about PrairieLearn because it's open-source and free, far superior to those paid websites with mandatory textbooks. I generally enjoy TV shows (I'm a big fan of Game of Thrones), hiking, and exploring. You can usually find me in UBC's library."

2023-05-31 09:01 UTC, firasm approved these changes

2023-05-31 09:02 UTC, merged

2023-05-31 09:02 UTC, firasm commented
Thanks @naclsodium !

2023-06-01 01:55 UTC, Moon0256 reviewed
Looks perfect